[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production]
  command = "npm run build"
  publish = ".next"

[context.deploy-preview]
  command = "npm run build"
  publish = ".next"

[context.branch-deploy]
  command = "npm run build"
  publish = ".next"
